"use client";

/**
 * EPIC-3 UC-03C — Real-Time Clinical Insights hook.
 * Generative: clinical-ai-facade → AiService consultation-assist (governed).
 * State: Medical Copilot sessionStorage only — never EMR.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { getConsultationAssist } from "@/lib/clinical-ai-facade";
import { getApiErrorMessage } from "@/lib/heydoctor-api";
import {
  buildLiveInsightsAssistRequest,
  mapAssistToLiveClinicalInsights,
  type LiveClinicalInsightsBatch,
} from "@/lib/epic3/live-clinical-insights";
import {
  clearLiveClinicalInsightsBatch,
  loadLiveClinicalInsightsBatch,
  saveLiveClinicalInsightsBatch,
} from "@/lib/epic3/live-clinical-insights-session";
import type { LiveDocumentationQualityView } from "@/lib/epic3/live-documentation-quality";
import type { NestConsultation } from "@/lib/services/consultations";
import type { ClinicalFoundationBundle } from "@/lib/types/clinical-foundation";

export function useLiveClinicalInsights(input: {
  open: boolean;
  sessionId: string | null;
  sessionBootstrapping: boolean;
  consultation: NestConsultation | null;
  foundation: ClinicalFoundationBundle | null;
  documentationQuality: LiveDocumentationQualityView;
}): {
  batch: LiveClinicalInsightsBatch | null;
  loading: boolean;
  error: string | null;
  generate: () => Promise<void>;
  regenerate: () => Promise<void>;
  discardInsight: (id: string) => void;
} {
  const [batch, setBatch] = useState<LiveClinicalInsightsBatch | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const autoGeneratedFor = useRef<string | null>(null);

  useEffect(() => {
    if (!input.open || !input.sessionId) return;
    const cached = loadLiveClinicalInsightsBatch(input.sessionId);
    if (cached) {
      setBatch(cached);
      autoGeneratedFor.current = input.sessionId;
    }
  }, [input.open, input.sessionId]);

  const persist = useCallback((next: LiveClinicalInsightsBatch) => {
    setBatch(next);
    saveLiveClinicalInsightsBatch(next);
  }, []);

  const generate = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const request = buildLiveInsightsAssistRequest({
        consultation: input.consultation,
        foundation: input.foundation,
        documentationQuality: input.documentationQuality,
      });
      const { data } = await getConsultationAssist(request);
      const next = mapAssistToLiveClinicalInsights({
        sessionId: input.sessionId,
        aiRunId: data.aiRunId ?? null,
        promptVersion: data.promptVersion ?? null,
        assistiveOnlyNotice: data.assistiveOnlyNotice ?? null,
        recommendations: data.recommendations ?? [],
      });
      if (next.insights.length === 0) {
        setError(
          "El Copilot no devolvió insights utilizables. Puede regenerar.",
        );
      }
      persist(next);
      autoGeneratedFor.current = input.sessionId ?? "local";
    } catch (err) {
      setError(
        getApiErrorMessage(
          err,
          "No se pudieron generar insights clínicos en vivo.",
        ),
      );
    } finally {
      setLoading(false);
    }
  }, [
    input.consultation,
    input.foundation,
    input.documentationQuality,
    input.sessionId,
    persist,
  ]);

  const regenerate = useCallback(async () => {
    if (input.sessionId) clearLiveClinicalInsightsBatch(input.sessionId);
    setBatch(null);
    await generate();
  }, [generate, input.sessionId]);

  useEffect(() => {
    if (!input.open) return;
    if (input.sessionBootstrapping) return;
    const key = input.sessionId ?? "local";
    if (autoGeneratedFor.current === key) return;
    if (input.sessionId && loadLiveClinicalInsightsBatch(input.sessionId)) {
      autoGeneratedFor.current = input.sessionId;
      return;
    }
    autoGeneratedFor.current = key;
    void generate();
  }, [input.open, input.sessionId, input.sessionBootstrapping, generate]);

  const discardInsight = useCallback((id: string) => {
    setBatch((prev) => {
      if (!prev) return prev;
      const insights = prev.insights.filter((i) => i.id !== id);
      const next = { ...prev, insights, persistsToEmr: false as const };
      saveLiveClinicalInsightsBatch(next);
      return next;
    });
  }, []);

  return {
    batch,
    loading,
    error,
    generate,
    regenerate,
    discardInsight,
  };
}
