"use client";

/**
 * EPIC-3 UC-02B — Generate / edit / discard / regenerate interview suggestions.
 * Generative path: clinical-ai-facade → AiService consultation-assist (governed).
 * State: Medical Copilot session (sessionStorage) only — never EMR.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { getConsultationAssist } from "@/lib/clinical-ai-facade";
import { getApiErrorMessage } from "@/lib/heydoctor-api";
import {
  buildInterviewAssistRequest,
  mapAssistToInterviewSuggestions,
  type InterviewSuggestion,
  type InterviewSuggestionsBatch,
} from "@/lib/epic3/interview-suggestions";
import {
  clearInterviewSuggestionsBatch,
  loadInterviewSuggestionsBatch,
  saveInterviewSuggestionsBatch,
} from "@/lib/epic3/interview-suggestions-session";
import type { PreVisitContextView } from "@/lib/epic3/pre-visit-context";
import type { PreVisitQualitySignalsView } from "@/lib/epic3/pre-visit-quality-signals";
import type { ClinicalFoundationBundle } from "@/lib/types/clinical-foundation";

export function useSuggestedInterviewQuestions(input: {
  open: boolean;
  sessionId: string | null;
  /** True while Medical Copilot session bootstrap is still in flight. */
  sessionBootstrapping: boolean;
  preVisit: PreVisitContextView;
  qualitySignals: PreVisitQualitySignalsView;
  foundation: ClinicalFoundationBundle | null;
}): {
  batch: InterviewSuggestionsBatch | null;
  loading: boolean;
  error: string | null;
  generate: () => Promise<void>;
  regenerate: () => Promise<void>;
  updateSuggestion: (id: string, text: string) => void;
  discardSuggestion: (id: string) => void;
} {
  const [batch, setBatch] = useState<InterviewSuggestionsBatch | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const autoGeneratedFor = useRef<string | null>(null);

  useEffect(() => {
    if (!input.open || !input.sessionId) return;
    const cached = loadInterviewSuggestionsBatch(input.sessionId);
    if (cached) {
      setBatch(cached);
      autoGeneratedFor.current = input.sessionId;
    }
  }, [input.open, input.sessionId]);

  const persist = useCallback((next: InterviewSuggestionsBatch) => {
    setBatch(next);
    saveInterviewSuggestionsBatch(next);
  }, []);

  const generate = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const request = buildInterviewAssistRequest({
        preVisit: input.preVisit,
        qualitySignals: input.qualitySignals,
        foundation: input.foundation,
      });
      const { data } = await getConsultationAssist(request);
      const next = mapAssistToInterviewSuggestions({
        sessionId: input.sessionId,
        aiRunId: data.aiRunId ?? null,
        promptVersion: data.promptVersion ?? null,
        assistiveOnlyNotice: data.assistiveOnlyNotice ?? null,
        recommendations: data.recommendations ?? [],
      });
      if (next.suggestions.length === 0) {
        setError(
          "El Copilot no devolvió preguntas utilizables. Puede regenerar.",
        );
      }
      persist(next);
      autoGeneratedFor.current = input.sessionId ?? "local";
    } catch (err) {
      setError(
        getApiErrorMessage(
          err,
          "No se pudieron generar sugerencias de entrevista.",
        ),
      );
    } finally {
      setLoading(false);
    }
  }, [
    input.sessionId,
    input.preVisit,
    input.qualitySignals,
    input.foundation,
    persist,
  ]);

  const regenerate = useCallback(async () => {
    if (input.sessionId) clearInterviewSuggestionsBatch(input.sessionId);
    setBatch(null);
    await generate();
  }, [generate, input.sessionId]);

  useEffect(() => {
    if (!input.open) return;
    // Prefer session-scoped cache; wait until session bootstrap settles.
    if (input.sessionBootstrapping) return;
    const key = input.sessionId ?? "local";
    if (autoGeneratedFor.current === key) return;
    if (input.sessionId && loadInterviewSuggestionsBatch(input.sessionId)) {
      autoGeneratedFor.current = input.sessionId;
      return;
    }
    autoGeneratedFor.current = key;
    void generate();
  }, [input.open, input.sessionId, input.sessionBootstrapping, generate]);

  const updateSuggestion = useCallback(
    (id: string, text: string) => {
      setBatch((prev) => {
        if (!prev) return prev;
        const suggestions: InterviewSuggestion[] = prev.suggestions.map((s) =>
          s.id === id ? { ...s, text, edited: true } : s,
        );
        const next = { ...prev, suggestions, persistsToEmr: false as const };
        saveInterviewSuggestionsBatch(next);
        return next;
      });
    },
    [],
  );

  const discardSuggestion = useCallback((id: string) => {
    setBatch((prev) => {
      if (!prev) return prev;
      const suggestions = prev.suggestions.filter((s) => s.id !== id);
      const next = { ...prev, suggestions, persistsToEmr: false as const };
      saveInterviewSuggestionsBatch(next);
      return next;
    });
  }, []);

  return {
    batch,
    loading,
    error,
    generate,
    regenerate,
    updateSuggestion,
    discardSuggestion,
  };
}
